server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: nikhil
    url: jdbc:postgresql://localhost:5432/fraud
    password: nikhil0101
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true